; CUSTOM PALETTE
[color]

# Black
black-base = #15141b
black-01 = #020202
black-02 = #000000
black-03 = #545454
black-04 = #8B8989

# Red
red-base = #ff6767
red-01 = #7a2a2a
red-02 = #a33d3d
red-03 = #ff9999
red-04 = #ffd6d6

# Green
green-base = #61ffca
green-01 = #1e7a5f
green-02 = #33a986
green-03 = #8effdb
green-04 = #c9fff0

# Yellow / Orange
yellow-base = #ffca85
yellow-01 = #9a6a2d
yellow-02 = #c28d4c
yellow-03 = #ffdba8
yellow-04 = #fff1dc

# Blue
blue-base = #82e2ff
blue-01 = #2a6c7a
blue-02 = #4c9fb2
blue-03 = #a6eeff
blue-04 = #dbf9ff
blue-05 = #f0fdff

# Magenta / Purple
magenta-base = #a277ff
magenta-01 = #3d2a7a
magenta-02 = #6640c2
magenta-03 = #c2a6ff
magenta-04 = #e7dbff

# Cyan / Pink
cyan-base = #f694ff
cyan-01 = #7a2a7a
cyan-02 = #a84ca8
cyan-03 = #f7b8ff
cyan-04 = #fce3ff

# White
white-base = #edecee
white-01 = #6d6d6d
white-02 = #bdbdbd
white-03 = #f8f7f9
white-04 = #ffffff
